# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(960, 700)
        Widget.setMinimumSize(QtCore.QSize(960, 700))
        Widget.setMaximumSize(QtCore.QSize(960, 700))
        self.groupBox = QtWidgets.QGroupBox(Widget)
        self.groupBox.setGeometry(QtCore.QRect(30, 60, 571, 481))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 20, 551, 451))
        self.label.setObjectName("label")
        self.groupBox_2 = QtWidgets.QGroupBox(Widget)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 550, 901, 131))
        self.groupBox_2.setObjectName("groupBox_2")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox_2)
        self.textEdit.setGeometry(QtCore.QRect(10, 20, 881, 101))
        self.textEdit.setObjectName("textEdit")
        self.groupBox_3 = QtWidgets.QGroupBox(Widget)
        self.groupBox_3.setGeometry(QtCore.QRect(620, 480, 151, 61))
        self.groupBox_3.setObjectName("groupBox_3")
        self.lcdNumber = QtWidgets.QLCDNumber(self.groupBox_3)
        self.lcdNumber.setGeometry(QtCore.QRect(10, 20, 131, 31))
        self.lcdNumber.setObjectName("lcdNumber")
        self.groupBox_4 = QtWidgets.QGroupBox(Widget)
        self.groupBox_4.setGeometry(QtCore.QRect(780, 480, 151, 61))
        self.groupBox_4.setObjectName("groupBox_4")
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.groupBox_4)
        self.lcdNumber_2.setGeometry(QtCore.QRect(10, 20, 131, 31))
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.layoutWidget = QtWidgets.QWidget(Widget)
        self.layoutWidget.setGeometry(QtCore.QRect(29, 20, 901, 25))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_2.setEnabled(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_3.setEnabled(False)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.graphicsView = QChartView(Widget)
        self.graphicsView.setGeometry(QtCore.QRect(610, 60, 331, 411))
        self.graphicsView.setObjectName("graphicsView")

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "人数检测可视化界面"))
        self.groupBox.setTitle(_translate("Widget", "实时视频"))
        self.label.setText(_translate("Widget", "视频将显示在这里"))
        self.groupBox_2.setTitle(_translate("Widget", "控制台信息"))
        self.groupBox_3.setTitle(_translate("Widget", "当前人数"))
        self.groupBox_4.setTitle(_translate("Widget", "本日最大人数"))
        self.pushButton.setText(_translate("Widget", "连接摄像头"))
        self.pushButton_2.setText(_translate("Widget", "开启实时视频"))
        self.pushButton_3.setText(_translate("Widget", "关闭实时视频"))
        self.pushButton_4.setText(_translate("Widget", "本地读取【测试】"))
from PyQt5.QtChart import QChartView
